server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#
#    username:
#    password:
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update