server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://adultdinosaurdooley.cgser4ytrswq.ap-northeast-2.rds.amazonaws.com:3306/369project
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update


app:
  auth:
    tokenSecret: ${TOKEN_SECRET_KEY} # 토큰 보안키
    tokenExpiry: ${TOKEN_EXPIRY} # 액세스 토큰 만료 시간 (2시간)
    refreshTokenExpiry: ${REFRESH_TOKEN_EXPIRY} # 리프레시 토큰 만료 시간 (1일)

#s3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION_STATIC}
      auto: false
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET}
      product-bucket: ${AWS_S3_PRODUCT_BUCKET}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error